<div class="callfor-popup">
</div>
<script>
   require(
       [
           'jquery',
           'Magento_Ui/js/modal/modal'
       ],
       function (
           $,
           modal
       ){
            var modaloption = {
               type: 'popup',
               modalClass: 'modal-popup',
               responsive: true,
               innerScroll: true,
               clickableOverlay: true,
               title: 'Hey TM'
           };
           var callforoption = modal(modaloption, $('.callfor-popup'));
           $('.callfor-popup').modal('openModal');
        }
   );
</script>